@F:\source_code\permission1.SQL;
@F:\source_code\user_creation.SQL;
@F:\source_code\page_formatting.SQL;
@F:\source_code\install.SQL;
@F:\source_code\enter_and_maintain.pkh;
@F:\source_code\enter_and_maintain.pkb;
@F:\source_code\run_department.SQL;
@F:\source_code\run_employee.SQL;
@F:\source_code\run_annual_sal.SQL;
@F:\source_code\run_deduction.SQL;
@F:\source_code\run_tax.SQL;
@F:\source_code\run_attendance.SQL;
@F:\source_code\run_leaves.SQL;
@F:\source_code\run_lencash.SQL;
@F:\source_code\run_payslip.SQL;



